# Plugin by StormDev
# Made for the Bukkit Minecraft Server API

name: UltimatePluginUpdater
main: net.stormdev.bukkitmods.ultimatepluginupdater.main.main
version: 5
commands:
   upu:
        aliases: [ultimatepluginupdater]
        description: This shows all registered plugins
        usage: /<command> [Check] [Update <Plugin>] [Updateall] [Unregister <Plugin>] [Register <Plugin>] [Install <Plugin>] [DownloadUpdate <URL> <Dest>]
        permission: upu.upu
        permission-message: You don't have access to this command
        default: op
   upurl:
        aliases: [ultimatepluginupdaterurl]
        description: This command handles url updates
        usage: /<command> [Check] [Unregister <URL>] [Register <URL> <LocalFilePath>]
        permission: upu.upu
        permission-message: You don't have access to this command
        default: op